// there are for Unit
export const SELECT_UNIT = 'SELECT_UNIT'
export const ADD_UNIT_READY = 'ADD_UNIT_READY'

// there are for Skill
export const DRAW_SKILL_INFORMATION_WINDOW = 'DRAW_SKILL_INFORMATION_WINDOW'
export const REMOVE_SKILL_INFORMATION_WINFOW = 'REMOVE_SKILL_INFORMATION_WINDOW'
// export const EDIT_TODO = 'EDIT_TODO'
// export const COMPLETE_TODO = 'COMPLETE_TODO'
// export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
// export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
// export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'